/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
import java.sql.*;
import javax.swing.*;
import javax.xml.crypto.Data;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class karyawan extends javax.swing.JFrame {
    
    // Script variable statment
        Connection con = null;
	ResultSet rs = null;
	PreparedStatement pst = null;
	Statement statBrg;
	Boolean ada = false;

    /**
     * Creates new form karyawan
     */
        private void koneksi (){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                String url="jdbc:mysql://localhost/karyawan"; //url database
                String user="root"; //user database
                String pass=""; //password database
                con = DriverManager.getConnection(url,user,pass);
                statBrg = con.createStatement(rs.TYPE_SCROLL_SENSITIVE,rs.CONCUR_UPDATABLE);
                rs = statBrg.executeQuery("select * from karyawan");
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                System.exit(0);
            }
        }
        private void display(){
        try{
            String sql="select * from karyawan";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
        private void Clear(){
         jTextField1.setText(null);
         jTextField2.setText(null);
         jTextField3.setText(null);
    }
        
    public karyawan() {
        initComponents();
        koneksi();   //memanggil fungsi koneksi
        display(); // menggil fungsi dislay untuk menampilkan data ke table
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        btngJenKel = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        TSimpan = new javax.swing.JButton();
        TKeluar = new javax.swing.JButton();
        TEdit = new javax.swing.JButton();
        THapus = new javax.swing.JButton();
        Tclear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("      Data Karyawan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 180, 90));

        jLabel2.setText("ID Karyawan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, 40));

        jLabel3.setText("Nama Karyawan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 120, 40));

        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 110, 40));

        jLabel5.setText("Jabatan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 110, 30));

        jLabel6.setText("No Hp");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 110, 40));

        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 120, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 230, 40));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 230, 40));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 230, 40));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 230, 40));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 230, 40));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 230, 40));

        TSimpan.setText("Simpan");
        TSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(TSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, -1));

        TKeluar.setText("Keluar");
        TKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(TKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 90, -1));

        TEdit.setText("Edit");
        TEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEditActionPerformed(evt);
            }
        });
        getContentPane().add(TEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 80, -1));

        THapus.setText("Hapus");
        THapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THapusActionPerformed(evt);
            }
        });
        getContentPane().add(THapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 510, 80, -1));

        Tclear.setText("Clear");
        Tclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TclearActionPerformed(evt);
            }
        });
        getContentPane().add(Tclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 90, 30));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 820, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);// keluar
    }//GEN-LAST:event_TKeluarActionPerformed

    private void TEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEditActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            statBrg = con.createStatement();
            String SQL = "update karyawan SET id_karyawan = '"+jTextField1.getText()+"', nama_karyawan = '"+jTextField2.getText()+"', jenis_kelamin = '"+jTextField3.getText()+"', jabatan = '"+jTextField4.getText()+"', no_hp = '"+jTextField5.getText()+"', alamat = '"+jTextField6.getText()+"' WHERE id_karyawan = '"+jTextField1.getText()+"'";
            statBrg.executeUpdate(SQL);
            display();
            statBrg.close();
            con.close();
            Clear();
            JOptionPane.showMessageDialog(null, "berhasil edit");
        } catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_TEditActionPerformed

    private void THapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THapusActionPerformed
        // TODO add your handling code here:
         try{
            koneksi();
            statBrg = con.createStatement();
            String SQL = "DELETE FROM karyawan WHERE id_karyawan = '"+jTextField1.getText()+"'";
            statBrg.executeUpdate(SQL);
            display();
            statBrg.close();
            con.close();
            JOptionPane.showMessageDialog(null, "berhasil hapus");
        }catch (Exception exc){
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_THapusActionPerformed

    private void TSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSimpanActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            statBrg = con.createStatement();
            String SQL = "insert into karyawan values('"+jTextField1.getText()+"','"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+jTextField5.getText()+"','"+jTextField6.getText()+"')";
            statBrg.executeUpdate(SQL);
            display();
            statBrg.close();
            con.close();
            Clear();
            JOptionPane.showMessageDialog(null, "berhasil simpan");
        } catch(Exception exc){
           System.err.println(exc.getMessage()); 
        }
    }//GEN-LAST:event_TSimpanActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            koneksi();
            int row =jTable.getSelectedRow();
            String tabel_klik=(jTable.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from karyawan where id_karyawan='"+tabel_klik+"'");
            if(sql.next()){
                String karyawan = sql.getString("ID_karyawan");
                jTextField1.setText(karyawan);
                String nama = sql.getString("nama_karyawan");
                jTextField2.setText(nama);
                String jeniskelamin = sql.getString("jenis_kelamin");
                jTextField3.setText(jeniskelamin);
                String jabatan = sql.getString("jabatan");
                jTextField4.setText(jabatan);
                String nohp = sql.getString("no_hp");
                jTextField5.setText(nohp);
                String alamat = sql.getString("alamat");
                jTextField6.setText(alamat);
                
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_jTableMouseClicked

    private void TclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TclearActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_TclearActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TEdit;
    private javax.swing.JButton THapus;
    private javax.swing.JButton TKeluar;
    private javax.swing.JButton TSimpan;
    private javax.swing.JButton Tclear;
    private javax.swing.ButtonGroup btngJenKel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
